### ISSUE TITLE
Assets are not served in production mode. Possible readme problem

### ISSUE THREAD

**Issue by onsails** [teamon/play-navigator#2]
I have probem with serving assets in production mode with application generated by both `play stage` and `play dist` commands.
After digging into Play20 and play-navigator sources I found that navigator sends file name  to `Assets.at(path: String, file: String)` prefixed by `/` and asset path becomes something like `/public//stylesheets/bootstrap.css`.
The following fix in nav.scala resolved my problem and assets are being served in all modes (`play run`, `play stage`, `play start` and `play dist`):
`val assets      = GET   on "assets" / **                 to { s: String => Assets.at(path="/public", s.substring(1)) }`

**Comment by teamon** [comment]
Sorry for the delay.

I think it will be better if "foo" / *\* returned string without leading /. Thank's for pointing this out.

**Comment by onsails** [comment]
Cool, thanks @teamon!
