### ISSUE TITLE
Access to params

### ISSUE THREAD

**Issue by umairakeel** [teamon/play-navigator#4]
First - this is an awesome router, really like it... 

Now, is there any plan to support parameters like so 

GET   /client/:id              controllers.Clients.list(page: Int ?= 1)

**Comment by teamon** [comment]
IMO this is not part of the router. In my projects I use

``` scala
  def param(key: String)(implicit request: RequestHeader) = params(key) >>= (_.headOption)
```

and then

``` scala
def list() = Action {
  val page = param("page").map(_.toInt) | 0
}
```

**Comment by umairakeel** [comment]
Found that line on some OAuth sample and am using the same, works well too!

Thanks
